[package]
name = "bitpack"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[features]
test_framework = []

[dependencies]
cfg-if = "1.0.0"
